### ISSUE TITLE
[Feature Request] 明确用户当前做种/下载列表中各个任务的客户端和IP

### ISSUE THREAD

**Issue by tongyifan** [tjupt/issues#14]
**如果你的请求和你遇到的某些问题相关，请描述**
明确用户当前做种/下载列表中各个任务的客户端和IP，便于查看
此外在用户i客户端列表中列出当前活动数

**描述一下你预想的解决办法**

**还有其他可选的解决方式吗**

**Additional context**

**Comment by DravenTJU** [comment]
https://github.com/tjupt/tjupt/commit/71b2f87b63d293f15968c52a0849e14e762f9327
https://github.com/tjupt/tjupt/commit/895f339a5638cdf9ae54eea85fc63ffaf11e2d6d
done
