### ISSUE TITLE
[Feature Request] 种子不同等级的置顶用不同颜色的高亮显示

### ISSUE THREAD

**Issue by DravenTJU** [tjupt/issues#15]
https://tjupt.org/forums.php?action=viewtopic&topicid=17422&page=p198361#pid198361
规则施行后，由于只剩下“2x促销”，“高亮显示”基本算是名存实亡了，希望能把“高亮显示”这个功能移到置顶上，不同等级的置顶用不同颜色的高亮显示。（没有高亮区隔，眼睛容易看花……）

**Comment by nidbCN** [comment]
几个小疑问：
1. ~~已知无法同时设置高亮和置顶，但是设置为高亮的种子可以由用户手动购买竞价置顶，此时高亮的颜色遵守设置高亮的颜色还是新加入的置顶高亮的颜色？~~ 已得知促销高亮功能被注释，不需要考虑两者冲突
2. 如果用户没有勾选控制面板中“添加置顶图标”一项，是否还对置顶做高亮处理？
3. 针对问题2，是否需要修改控制面板，在其中添加一个“置顶种子”的选项，由用户选择“图标”、“高亮” 、“图标+高亮”？

**Comment by DravenTJU** [comment]
1. 以前的种子优惠高亮不打算要了，之后的普通种子和2x种子都以种子名称后面的标记（文本或图标）进行标识
2. 控制面板中我认为可以提供三个选项，添加一个“置顶种子”的选项，由用户选择a. 置顶图标 b. 置顶高亮 c. 置顶图标+高亮（c为默认选项）

**Comment by nidbCN** [comment]
> 1. 以前的种子优惠高亮不打算要了，之后的普通种子和2x种子都以种子名称后面的标记（文本或图标）进行标识
> 2. 控制面板中我认为可以提供三个选项，添加一个“置顶种子”的选项，由用户选择a. 置顶图标 b. 置顶高亮 c. 置顶图标+高亮（c为默认选项）

1. 是否需要我去 删除/注释/隐藏 控制面板里普通种子和2X中的“高亮显示”
2. 目前来说数据库中 `appendsticky` 这个字段，显示图标的为 `"yes"` ，更改之后默认值是 显示高亮+图标 ，~~有以下三种方案：~~
    1. ~~使用新的默认值（即 `"icon_highlight"` ）代替原来的 `"yes"` ，执行 `UPDATE users SET appendsticky = "icon_highlight" WHERE appendsticky = "yes";` 替换掉数据库中的值；~~
    2. ~~不改动数据库，`yes` 和 `icon_highlight` 均为高亮+图标，在用户更改设置保存时将以前的 `yes` 提交为 `icon_highlight`；~~
    3. ~~使用 `yes` 代表高亮+图标，而不是 `icon_highlight`，这样改动最少，但是可能会迷惑到后来者（那段代码不是特别方便留注释）；~~
  查看了一下表的结构，发现 `appendsticky` 是 `enum('yes','no')`，需要把该列数据类型改为 `enum('icon_highlight','highlight','icon','off')` 并将原来为 'yes' 值改为 'icon_highlight' ，为 `no` 的值改为 `off`，需要执行以下操作：
    ```sql
    # 不会SQL，仅供参考，有待优化
    ALTER TABLE users MODIFY appendsticky ENUM('icon_highlight','highlight','icon','off', 'yes', 'no');
    UPDATE users SET appendsticky = "icon_highlight" WHERE appendsticky = "yes";
    UPDATE users SET appendsticky = "off" WHERE appendsticky = "no";
    ALTER TABLE users ALTER COLUMN appendsticky DROP default;
    ALTER TABLE users ALTER COLUMN appendsticky SET default "icon_highlight";
    ALTER TABLE users MODIFY appendsticky ENUM('icon_highlight','highlight','icon','off');
    ```
    我不知道上述方案在 TJUPT 庞大的数据量下是否可以，如果该 SQL 语句优化后依旧无法应用于 TJUPT，则可以考虑将控制面板处的置顶做成： “高亮+图标” 或 “不显示任何标记”。

**Comment by DravenTJU** [comment]
1. 需要注释掉种子优惠高亮的相关部分，去掉控制面板-促销种子中的“高亮显示”选项，对数据库中该选项的值改为添加图标的值
2. 该方案可行👍

**Comment by nidbCN** [comment]
1. 促销的默认值为“添加标记，如'2X免费'”，改成默认值是不是好一些？对应的数据库操作：
    ```sql
    UPDATE users SET appendsticky = "word" WHERE appendsticky = "highlight";
    ALTER TABLE users MODIFY appendpromotion ENUM('word','icon','off');
    ```
3. 关于控制面板中置顶种子一块，昨晚和杯具讨论了一下，确实有用户设置原来 不显示置顶图标 的选项，那么现在的选项就是：
a. 高亮+图标 b. 图标 c. 高亮 d. 关闭  
是否太多了一点？
