### ISSUE TITLE
[BUG] 动漫板块未能细分动画与漫画

### ISSUE THREAD

**Issue by lengdong863** [tjupt/issues#25]
**描述Bug**
发布“漫画”时，在选择“漫画”后，下方的一些选项依然显示“动漫XX”。

**预期的行为**
将“动漫类别”刚在首位，选择不同选项后，根据相关发种要求，下方选项变动。
例如，选择“漫画”后，下方变为“漫画集数”、“漫画文件格式”、“漫画国别”。
而不是原来的“动漫集数”、“动漫文件格式”、“动漫国别”。

**Comment by issaccv** [comment]
@YoungJack068  我认为这不是一个bug，从日语的Manga和英文的Animation在中文语义下统称为动漫，即动画和漫画。

**Comment by lengdong863** [comment]
> @YoungJack 我认为这不是一个虫子，从日语的漫画和中文的动画在中文下统称为动漫，即漫画漫画。

不算bug的话，就把“动漫类资源发布规则及注意事项”的相关描述改一下吧，这对新手来说真的很有用。

**Comment by DravenTJU** [comment]
@YoungJack068 请具体说一下哪些相关描述，改成什么样的

**Comment by lengdong863** [comment]
> @YoungJack068 请具体说一下哪些相关描述，改成什么样的
3.2.2、漫画集数：
改为：3.2.2、动漫集数：
发布页面补充，漫画集数的示例：[Vol.01-Vol.12]。
3.2.3、漫画类别：
改为：3.2.3、动漫类别：
发布页面补充，[完结]、[未完结]的说明。
