### ISSUE TITLE
[Feature Request] 优化短讯箱操作逻辑

### ISSUE THREAD

**Issue by DravenTJU** [tjupt/issues#29]
**如果你的请求和你遇到的某些问题相关，请描述**
每当我收到一堆短讯，就需要一个一个手动点开才能看到短讯正文”

**描述一下你预想的解决办法**
单独分出一个未读箱，像ourbits那样直接展示短讯正文，在末尾加一个全部设为已读的按钮，点击后跳转至下一页未读短讯或收件箱

**还有其他可选的解决方式吗**

**Comment by lengdong863** [comment]
鼠标悬浮在站内信标题上，显示短讯内容。
类似标题过长时，悬浮显示完整标题。
这样可否？

**Comment by DravenTJU** [comment]
done by https://github.com/tjupt/tjupt/commit/4bd72c67ad624808c7dcf54e488a30f44c754a0f
