### ISSUE TITLE
[Feature Request] 优化文件过滤机制

### ISSUE THREAD

**Issue by DravenTJU** [tjupt/issues#34]
**如果你的请求和你遇到的某些问题相关，请描述**
每当用户发布MNHD CMCT之类的，就会问违反了哪条规则

**描述一下你预想的解决办法**

1. 优化banned_file_type和bannedtitle两个表的字段，增加“返回给用户的提示”一列，增加启用或关闭的开关
2. 在拦截转候选的同时，返回用户被拦截的原因
3. 增删规则的操作写入日志

**Comment by DravenTJU** [comment]
![image](https://user-images.githubusercontent.com/22270833/174119874-268ba568-3e7e-41eb-a5cb-1bce8231367b.png)

**Comment by nidbCN** [comment]
1. 表 `banned_file_type` 中增加 `reason` 列
2. 原代码采用正则表达式来处理文件名，难以定位具体存在的问题，是否可以取消使用正则表达式而采用其他方法（遍历规则列表）等进行排查，同时数据库内类似于 `.rmvb$` 这种值应改成 `.rmvb`

**Comment by DravenTJU** [comment]
@nidbCN 1. banned_file_type和bannedtitle两个表应该可以合二为一，字段应包括id, catid, added, until, type(for title, for file, both), keywords, reason, addedby, enabled
2. 可以改成遍历，文件扩展名不需要与文件名作区分了吗？

**Comment by nidbCN** [comment]
1. 我还没看那个表

> @nidbCN 1. banned_file_type和bannedtitle两个表应该可以合二为一，字段应包括id, catid, added, until, type(for title, for file, both), keywords, reason, addedby 2. 可以改成遍历，文件扩展名不需要与文件名作区分了吗？

1. 应该可以合并
2. 文件拓展名和文件名可以轻易区分开的，分别做检测就行 ![image](https://user-images.githubusercontent.com/36162655/179181598-4e4967e1-7ba7-4775-b1dc-89bfc54e475c.png)

**Comment by DravenTJU** [comment]
@nidbCN OK

**Comment by DravenTJU** [comment]
BTW，除了对标题和文件名过滤之外，简介应该也加入此过滤机制，那么type应包含title, file, descri, tittle&file, all

**Comment by DravenTJU** [comment]
（还有
通过种子hash拦截同样的种子，减少违规种子重复性上传，检查hash的时候只检查活种和非因断种被删的种子，并返回用户这个种子之前被删除的原因类型

**Comment by nidbCN** [comment]
希望能够将代码中硬编码的文件类型：`.qsv` `.kux` `.torrent` `.!ut` `.url` `.qdl2` `.td` `.tdl` `.td.cfg` `.tmp` `xv` 存储于数据库中，不过这些类型是对任意 catid 均通用的，或许可以将他们的 catid 设置为 `400` 或某个特殊值，然后修改查询的 SQL 语句

**Comment by DravenTJU** [comment]
https://github.com/tjupt/tjupt/commit/21daccb6ad49e5a7ee4f06a7f3029dc7cb448923
