### ISSUE TITLE
[BUG] 21 点计算错误

### ISSUE THREAD

**Issue by CuiYongen** [tjupt/issues#35]
**描述Bug**
![image](https://user-images.githubusercontent.com/12591929/164069404-cfe754ca-e2a2-4eda-932b-7e1a8028af3f.png)
![image](https://user-images.githubusercontent.com/12591929/164071101-cedd47b0-88c8-4f70-a0cd-ef534c7f76bc.png)

遇到过好几次，请问这里计算逻辑到底是什么。。

**复现方法**
靠运气复现，印象中好像数字特别小的时候容易出现这个 bug（不确定）

**预期的行为**
以上图为例，A 的值应该为 1，总和应为 17

**Comment by CuiYongen** [comment]
![image](https://user-images.githubusercontent.com/12591929/164070982-09db8ae1-4766-4381-8e61-daae4dbee774.png)

**Comment by Rhilip** [comment]
@CuiYongen 上图时，总和应该为17，因为
A在总分不超过21时作11，总分超过21则作1。J,Q,K作为10。

**Comment by CuiYongen** [comment]
> @CuiYongen 上图时，总和应该为17，因为 A在总分不超过21时作11，总分超过21则作1。J,Q,K作为10。

是的是的，少打了一个 1
