### ISSUE TITLE
[Feature Request] 趣味盒评论区保留

### ISSUE THREAD

**Issue by ColderCoder** [tjupt/issues#38]
往期趣味盒在日志里只剩本体，评论不可见（被丢弃了?）

**描述一下你预想的解决办法**
一期存储为一个topic？或许可以单独成一个站内BBS分区，这样也方便射魔，查看&评论往期。也可考虑低等级用户花费魔力值（临时或永久）获得该板块访问权的道具。

**还有其他可选的解决方式吗**
目前是归档在日志下面，如果要实现看往期评论或许方便，但评论往期感觉不太好搞 (?)

**Comment by DravenTJU** [comment]
趣味盒已完成重构，上面提到的已全部实现
