### ISSUE TITLE
[Feature Request] 添加请求辅种功能

### ISSUE THREAD

**Issue by Alozxy** [tjupt/issues#39]
**如果你的请求和你遇到的某些问题相关，请描述**
不管是在新手群还是论坛，总是经常有人询问：某个种子明明有人做种，为什么我却没有下载速度。 诸如此类的问题，大部分是因为做种的人和下载的人都处于内网，所以无法互相连接导致的。

**描述一下你预想的解决办法**
可以模仿求种功能，添加一个请求辅种功能。请求者使用魔力值发布要求，由具有公网ip的人接受请求并下载相应种子，然后再做种上传给请求者。由于公网ip的可连接性，可以与两个内网用户连通。最后请求者下载完成后提交魔力值给接收者。

**还有其他可选的解决方式吗**
如果能有其他方案，也请一并给出吧

**Additional context**

**Comment by DravenTJU** [comment]
这个需求可以通过竞价置顶和求种区得到满足
