### ISSUE TITLE
[BUG] 茉莉园碰运气在魔力值小于1000时无法修改使用的魔力值

### ISSUE THREAD

**Issue by aimerneige** [tjupt/issues#40]
**描述Bug**
请清晰的描述bug

茉莉园碰运气在魔力值小于 1000 时尝试修改使用的魔力值，界面不会刷新，依然显示“需要更多魔力值”

**复现方法**
复现bug所需操作：

魔力值小于 1000 时尝试使用小于 1000 的魔力值碰运气。

**预期的行为**
请描述你预期发生的事件

输入小于 1000 的魔力值时界面会更新。

**屏幕截图**
如果可能的话请用屏幕截图更清晰的描述bug

![image](https://user-images.githubusercontent.com/51701792/185543311-e3b8ea16-46ba-417e-b70d-7927fc88be77.png)

**使用环境（请尽可能的完善以下信息）**
 - 操作系统: [e.g. iOS] Linux fedora 36
 - 浏览器: [e.g. chrome, safari] chrome
 - 浏览器版本: [e.g. 22] Version 104.0.5112.79 (Official Build) (64-bit)
 - 用户ID: [e.g. 59129] AimerNeige

**额外信息**
任何你觉得与此bug相关的信息

**Comment by DravenTJU** [comment]
这个其实也不能算作bug，是需要当前魔力值大于1000才能碰运气
我修改了一下项目说明，明确了一下当前魔力值需≥1000
