### ISSUE TITLE
[BUG]”本主题回帖内容仅楼主可见“在楼主回复层失效

### ISSUE THREAD

**Issue by xuanzha** [tjupt/issues#45]
**描述Bug**
贴中“---本主题回帖内容仅楼主可见---“的内容当楼主回复后能在楼主那层看到内容

**复现方法**
无特殊操作，正常进入论坛后进入帖子就会出现（例子出处为：邀请注册区 >  【个人邀请】日韩音乐站：JPOP*不限（长期发放）【不欢迎NTR】 ）

**预期的行为**
仅楼主可见的内容在楼主层也为其他用户不可见

**屏幕截图**

**使用环境（请尽可能的完善以下信息）**
 - 操作系统: [PC]
 - 浏览器: [Edge]
 - 浏览器版本: [117.0.2045.36 (正式版本) (64 位)]
 - 用户ID: [xuanzha]

**额外信息**
无

**Comment by DravenTJU** [comment]
这个其实不算bug。
你截图的回帖内容是在“仅楼主可见“这个功能上线之前发布的，在推出这个功能之后，因为楼主的回帖内容是所有人可见的，非楼主的回帖都不允许引用了。
截图有隐私信息，删除了。
