### ISSUE TITLE
[Feature Request] BBCode mediainfo tag 支持

### ISSUE THREAD

**Issue by tongyifan** [tjupt/issues#9]
**如果你的请求和你遇到的某些问题相关，请描述**
加个像PTP那样的mediainfo框

**描述一下你预想的解决办法**
一些现有parser实现
https://github.com/bhutanio/mediainfo-parser
https://github.com/HDVinnie/MediaInfo-Helper

**还有其他可选的解决方式吗**

**Additional context**

**Comment by DravenTJU** [comment]
done.
https://github.com/tjupt/tjupt/commit/efea8cd327dd76e3c053c0aec97f8de1505bef89
